knp_paginator:
    page_range: 5                      # nombre de liens de page affichés
    default_options:
        page_name: page                # nom du paramètre de page
        sort_field_name: sort          # nom du paramètre de tri
        sort_direction_name: direction # nom du paramètre de direction
        distinct: true                 # garantir des résultats distincts
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' 