services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

  php:
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
    networks:
      - symfony_network

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sym64enez
      MYSQL_PASSWORD: enez
      MYSQL_USER: symenez
      MYSQL_ROOT_PASSWORD: enez
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - symfony_network

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - symfony_network

networks:
  symfony_network:

volumes:
  database_data:
