version: '3.1'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony_network

  php:
    build: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - database
    networks:
      - symfony_network
    environment:
      DATABASE_URL: "mysql://symenez:enez@database:3306/sym64enez?serverVersion=8.0.32&charset=utf8mb4"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_PASSWORD=enez
      - PMA_USER=symenez
    depends_on:
      - database
    networks:
      - symfony_network

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sym64enez
      MYSQL_PASSWORD: enez
      MYSQL_USER: symenez
      MYSQL_ROOT_PASSWORD: enez
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - symfony_network

networks:
  symfony_network:

volumes:
  database_data:
